---
- name: play1
  hosts: local
  connection: local
  tasks:
  - name: play1 and task1
    ansible.builtin.debug:
      msg: "Hello from Play1 and Task1" 

  - name: play1 and task2
    ansible.builtin.debug:
      msg: "Hello from play1 and Task2"


- name: play2
  hosts: local
  connection: local
  tasks:
  - name: Play2 and Task 1
    ansible.builtin.debug:
     msg: "Hello from Play2 and Task1"
     

  - name: Play2 and Task2
    ansible.builtin.debug:
      msg: "Hello from Play2 and Task2"           
