---
- name: variables from files
  hosts: local
  connection: local
  vars_files:
  - course.yml

  tasks:
  - name: printingthe variable
    ansible.builtin.debug:
      msg: "hello course name : {{ COURSE }}, duration : {{ DURATION }}, trainer is : {{ TRAINER }}"