[local]
localhost


[frontend]
172.31.18.72 COURSE=ANSIBLE DURATION=120HRS TRAINER=satyam ansible_user=ec2-user ansible_password=DevOps321
172.31.18.6 COURSE=devscops DURATION=12HRS TRAINER=satyam ansible_user=ec2-user ansible_password=DevOps321

[local:vars]
COURSE= Devops
DURATION= 12HRS
TRAINER= satyam
GREETING= "hello from inventory"